#define MAX_REC_LEN 255

//#define VERBOSE

/*

OBSOLETE: Values in build_host.h should be used instead. PLEASTE NOTE: the file is autogenerated during the build process.

#define BRIGHTNESSFILE "/proc/acpi/video/OVGA/DD03/brightness"
#define SRCHSTR "current:"
const unsigned short levels[] = {10, 25, 35, 50, 60, 75, 90, 100};
*/

#include "build_host.h"
