/*
OBSOLETE: Values in build_host.h should be used instead. PLEASTE NOTE: the file is autogenerated during the build process.

#define BRIGHTNESSFILE "//sys/devices/virtual/backlight/acpi_video0/brightness"
#define MAXVALUE       7

//#define VERBOSE  <== normally defined in the Makefile

*/

#include "build_host.h"
